version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mem0-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.26.0
    container_name: mem0-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/mem0password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: mem0-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=mem0
      - POSTGRES_PASSWORD=mem0password
      - POSTGRES_DB=mem0db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped